app_version: 0.4.0-windows_beta.2
behavior_configs:
- base_move_speed: 5.0
  base_wheel_speed: 0.3
  free_mode_auto_off_s: 0
  grid_action_level: subgrid
  hide_cursor_on_click: false
  hide_location: bottom_left
  initial_action_location: system_cursor
  initial_overlay_monitor: with_mouse
  move_duration_ms: 100
  move_real_cursor_with_virtual: true
  move_speed_multiplier: 3.0
  movement_easing: 0.1
  multi_action_timeout_ms: 400
  name: main_behavior
  send_escape_after_global_alt_tap__windows: true
  tap_threshold_ms: 250
  wheel_easing: 0.1
  wheel_speed_multiplier: 4.0
  wheel_step_size: 2.0
  wheel_step_size_large: 10.0
classname: AppConfig
custom_monitor_assignments: []
display_input: none
event_tap_location: hid_head
grid_configs:
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    keys: ASDFG HJKL;
    num_cells_x: 10
    num_cells_y: 1
  - border_width: 1.0
    callback: build_cell_strings
    keys: QWERT YUIOP ASDFG HJKL; ZXCVB NM,./
    num_cells_x: 1
    num_cells_y: 30
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    keys: ''
    num_cells_x: 2
    num_cells_y: 1
  hold_subgrid_key_for_nudge: false
  name: position_based_columns
  nudges_per_cell: 4
  strategy: subgrid
  subgrid_dims:
  - 10
  - 3
  subgrid_mouse_action_keys: QWERT YUIOP ASDFG HJKL; ZXCVB NM,./
keyboard_layout: null
keymaps:
- entries:
    back mouse button: null
    back mouse button (w/o overlay): null
    close UI element: Escape
    cycle click count: null
    cycle font: '3'
    cycle font reverse: shift+3
    cycle grid action level: '2'
    cycle mouse action type: null
    cycle mouse button: null
    decrease overlay opacity: ArrowDown
    edit config: Tab
    enter free mode: AltLeft tap
    execute mouse action: Space
    execute mouse move: CtrlLeft tap
    exit free mode: Escape
    forward mouse button: null
    forward mouse button (w/o overlay): null
    hide overlay: Escape
    hold for back button: null
    hold for drag: CtrlLeft
    hold for forward button: null
    hold for middle button: AltLeft
    hold for move: null
    hold for right button: Shift
    hold for speed decrease: null
    hold for speed increase: ShiftLeft
    increase overlay opacity: ArrowUp
    jump to bottom: null
    jump to left edge: null
    jump to right edge: null
    jump to top: null
    left mouse button: Space
    left mouse button (w/o overlay): null
    middle mouse button: C
    middle mouse button (w/o overlay): null
    move down: j
    move left: h
    move right: l
    move up: k
    release hold/drag: Escape
    repeat last mouse action: null
    right mouse button: V
    right mouse button (w/o overlay): null
    show overlay: CtrlLeft tap
    subgrid nudge down:
    - D
    - K
    subgrid nudge left:
    - S
    - J
    subgrid nudge right:
    - F
    - L
    subgrid nudge up:
    - E
    - I
    switch monitor left: ShiftLeft tap
    switch monitor right: ShiftRight tap
    toggle continuous mode: '1'
    toggle continuous mode until closed: null
    toggle free mode: null
    toggle overlay: null
    toggle overlay lock: null
    undo last key: Backspace
    wheel down: d
    wheel down fast: null
    wheel left: null
    wheel left fast: null
    wheel right: null
    wheel right fast: null
    wheel step down: null
    wheel step down large: null
    wheel step left: null
    wheel step left large: null
    wheel step right: null
    wheel step right large: null
    wheel step up: null
    wheel step up large: null
    wheel up: u
    wheel up fast: null
  name: mac
monitor_assignment_mode: auto
name: ''
style_configs:
- always_on_subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.2
  background_rgba:
  - 0.5725490196078431
  - 0.5725490196078431
  - 0.5725490196078431
  - 0.4
  char_spacing_cell_width_ratio: 0.5
  char_spacing_font_size_ratio: 0.5
  char_spacing_strategy: cell_width_relative
  cursor_drag_rgba:
  - 0.0
  - 0.5
  - 1.0
  - 0.7
  cursor_move_rgba:
  - 0.75
  - 0.41
  - 0.92
  - 0.7
  cursor_other_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.7
  cursor_rgba:
  - 0.4588235294117647
  - 0.9725490196078431
  - 0.4588235294117647
  - 0.8
  cursor_right_button_rgba:
  - 0.92
  - 0.32
  - 0.32
  - 0.7
  cursor_size: 7
  font_family: Bahnschrift Condensed
  font_size_multiplier: 0.4
  font_weight: 500
  grid_line_style: lines
  grid_rgba:
  - 0.5450980392156862
  - 0.5490196078431373
  - 0.5450980392156862
  - 0.5
  highlight_animation_ms: 0
  highlight_rgba:
  - 0.0
  - 0.00392156862745098
  - 0.00392156862745098
  - 0.4
  name: default
  show_initial_highlight: false
  subgrid_font_size_multiplier: 0.75
  subgrid_rgba:
  - 0.611764705882353
  - 0.615686274509804
  - 0.611764705882353
  - 0.5
  subgrid_text_rgba:
  - 0.996078431372549
  - 0.996078431372549
  - 0.9921568627450981
  - 1.0
  text_rgba:
  - 0.996078431372549
  - 0.9921568627450981
  - 0.9921568627450981
  - 1.0
  text_shadow_blur_radius: 2.0
  text_shadow_offset:
  - 0.0
  - 0.0
  text_shadow_rgba:
  - 0.0392156862745098
  - 0.0392156862745098
  - 0.0
  - 1.0
  text_y_offset: 0.0
  window_opacity: 1.0 window_opacity: 1.0
